// import { Component, OnInit } from '@angular/core';
// import { NavbarComponent } from '../navbar/navbar.component';
// import { FormsModule } from '@angular/forms';
// import { ProductService } from '../../../services/products.service';
// import { Products } from '../../../models/products';

// @Component({
//   selector: 'app-menu',
//   standalone: true,
//   imports: [NavbarComponent, FormsModule],
//   templateUrl: './menu.component.html',
//   styleUrl: './menu.component.css'
// })
// export class MenuComponent implements OnInit {
//   products: Products[] = [];
//   constructor(
//     private productservice: ProductService
//   ) { }

//   ngOnInit(): void {
//     this.productservice.getAllProducts().subscribe((response: Products[]) => {
//       this.products = response;
//     });
//   }
// }


import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';  // Import CommonModule
import { ProductService } from '../../../services/products.service';
import { PaginatorProducts, Products } from '../../../models/products';
import { FormsModule } from '@angular/forms';
import { Categories } from '../../../models/categories';
import { CartService } from '../../../services/carts.service';
import { Carts } from '../../../models/carts';
import { NavbarComponent } from "../navbar/navbar.component";
import { FooterComponent } from '../footer/footer.component';

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [CommonModule, FormsModule, NavbarComponent, FooterComponent],  // Include CommonModule here
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {
  categories: Categories[] = [];
  products: PaginatorProducts = { data: [] };
  productsList: Products[] = [];
  selectedItem: Products | null = null;
  quantity: number = 1;

  constructor(private productService: ProductService, private cartService: CartService) {}

  ngOnInit(): void {
    this.productService.getAllProducts().subscribe((response: Products[]) => {
      this.productsList = response;
    });
  }

  addToCart(productId: number, quantity: number, thumbnail:string) {
    const newCartItem = {
      cartId: 0, // Set cartId to 0 or handle this as needed (e.g., auto-generated by backend)
      userId: 1001, // Replace with the actual userId
      products: [{ productId, quantity, thumbnail }],
      total: quantity * this.selectedItem!.price, // Assuming total is based on the selected item's price
      
    };
  
    this.cartService.addCart(newCartItem).subscribe((response: Carts) => {
      console.log('Cart updated:', response);
    });
  }
  selectItem(item: Products): void {
    this.selectedItem = item;
    this.quantity = 1; // Reset quantity each time a new product is selected
  }
}

