import { Component, inject, Injectable, OnInit } from '@angular/core';
import { ProductService } from '../../../services/products.service';
import { FormsModule } from '@angular/forms';
import {
  PaginatorProducts,
  Products as Product,
  Products,
} from '../../../models/products';
import { HttpClient } from '@angular/common/http';
import { CategoryService } from '../../../services/categories.service';
import { Categories } from '../../../models/categories';
import { Router } from '@angular/router';
import { CartService } from '../../../services/carts.service';
import { Carts } from '../../../models/carts';
import { FooterComponent } from '../footer/footer.component';
import { NavbarComponent } from '../navbar/navbar.component';

@Injectable({
  providedIn: 'root',
})
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [FormsModule, FooterComponent, NavbarComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
})
export class HomeComponent implements OnInit {
  categories: Categories[] = [];
  products: PaginatorProducts = { data: [] };
  productsList: Products[] = [];
  selectedItem: Products | null = null;
  quantity: number = 1;

  constructor(
    private http: HttpClient,
    private productService: ProductService,
    private cartService: CartService,
    private categoryService: CategoryService,
    private productServices: ProductService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.productService
      .getProducts()
      .subscribe((response: PaginatorProducts) => {
        this.products = response;
      });

    this.categoryService.getCategories().subscribe((response: Categories[]) => {
      this.categories = response;
    });
  }

  previousPage() {
    this.productService
      .getProducts()
      .subscribe((response: PaginatorProducts) => {
        this.products = response;
      });
  }

  nextPage() {
    this.productService
      .getProducts()
      .subscribe((response: PaginatorProducts) => {
        this.products = response;
      });
  }

  gotoPage() {
    this.productService
      .getProducts()
      .subscribe((response: PaginatorProducts) => {
        this.products = response;
      });
  }

  productPaginate(product: ProductService) {
    let apiUrl = 'http://localhost:3000/categories?_page=1&_per_page=3';
    return apiUrl;
  }

  categoriesData() {
    this.categoryService.getCategories().subscribe((response: Categories[]) => {
      this.categories = response;
      console.log(this.categories);
    });
  }

  // selectItem(item: Products): void {
  //   this.selectedItem = item;
  // }

  selectItem(item: Products): void {
    this.selectedItem = item;
    this.quantity = 1; // Reset quantity each time a new product is selected
  }

  addToCart(productId: number, quantity: number, thumbnail: string) {
    const newCartItem = {
      cartId: 0, // Set cartId to 0 or handle this as needed (e.g., auto-generated by backend)
      userId: 1001, // Replace with the actual userId
      products: [{ productId, quantity, thumbnail}],
      total: quantity * this.selectedItem!.price, // Assuming total is based on the selected item's price
      
    };
  
    this.cartService.addCart(newCartItem).subscribe((response: Carts) => {
      // alert('Cart updated:');
      alert('Cart updated:');

      console.log('Cart updated:', response);
    });
  }

  openMenu() {
    // 3 second loading enimation when method is called
    setTimeout(() => {
      this.router.navigate(['menu']);
    }, 1500);
  }
}
